# Generated by Django 4.2.7 on 2026-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Тип отпуска')),
            ],
            options={
                'verbose_name': 'Тип отпуска',
                'verbose_name_plural': 'Типы отпусков',
                'db_table': 'leave_types',
            },
        ),
    ]
